### ISSUE TITLE
Nice to have: Create well-described releases from tags

### ISSUE THREAD

**Issue by myhau** [VirtuslabRnD/pulumi-kotlin#189]
- maybe we could include the changelog and potential breaking changes?

**Comment by jplewa** [comment]
This is what the `publish` section in `prepare_release.yml` should look like:
```yml
  publish:
    name: Publish packages
    needs: tag
    runs-on: self-hosted
    if: ${{ needs.tag.outputs.is_release == 'true' }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        provider: [
          cloudflare, slack, github, random, gcp, google-native, aws, aws-native, azure, azure-native, kubernetes,
          nomad, docker, gitlab, digitalocean, alicloud
        ]
    steps:
      - id: provider
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ matrix.provider }}
      - name: Check out project sources
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Publish packages
        run: ./gradlew publishPulumi${{ matrix.provider }}PublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version
        id: version
        run: >-
          echo "::set-output name=VERSION::$(
            file_name=$(ls ./build/libs/pulumi-${{ matrix.provider }}-*-javadoc.jar | xargs -n 1 basename)
            echo $file_name | sed -e "s/^pulumi-${{ matrix.provider }}-kotlin-//" -e "s/-javadoc.jar$//"
          )"
      - name: Rename Dokka directory before upload
        run: |
          mkdir -p ./docs/${{ matrix.provider }}/${{ steps.version.outputs.VERSION }}
          mv ./build/dokka/pulumi${{ steps.provider.outputs.capitalized }}Javadoc/* ./docs/${{ matrix.provider }}/${{ steps.version.outputs.VERSION }}
      - name: Install Rclone
        run: |
          yum -y install unzip
          curl https://rclone.org/install.sh | bash || true
      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          cp .github/workflows/rclone.conf ~/.config/rclone/rclone.conf
          echo "$GCP_SERVICE_ACCOUNT_FILE" > ~/.config/gcp-key.json
        env:
          # pulumi-kotlin-docs service account key created manually through GCP UI and added manually to GitHub by @myhau (Michal Fudala)
          GCP_SERVICE_ACCOUNT_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_FILE }}
      - name: Upload Dokka artifacts
        run: |
          rclone copy --transfers=1024 ./docs/${{ matrix.provider }} rclone-jvm-lab:/pulumi-kotlin-docs/${{ matrix.provider }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/libs/*.jar
          tag: ${{ matrix.provider }}/v${{ steps.version.outputs.VERSION }}
          body: ??
```
These are the differences:
![image](https://user-images.githubusercontent.com/34098778/207626063-ffc1579f-f4cc-4f2f-9d87-daa22b9b4121.png)
